### ISSUE TITLE
Would be amazing to add the data for gambier/keats

### ISSUE THREAD

**Issue by davidascher** [samuel-pratt/bc-ferries-api#11]
The relevant page is at https://www.bcferries.com/routes-fares/schedules/gambier-keats

unfortunately it is in a very much non-standard format.

**Comment by samuel-pratt** [comment]
Do you know a good way to add the data to the current structure? I could add it in the scraper but I'm not sure how to display it in the API .

**Comment by davidascher** [comment]
The timetable is hard to read but the logic should apply just fine to your existing API.  The ports in question are Langdale, Gambier and Keats although the latter two could probably be labeled New Brighton and Keats Landing.

**Comment by samuel-pratt** [comment]
Closing for the reason commented here: https://github.com/samuel-pratt/bc-ferries-api/issues/24#issuecomment-1074490946
