### ISSUE TITLE
Missing smaller ports

### ISSUE THREAD

**Issue by hanskrohn** [samuel-pratt/bc-ferries-api#22]
Wondering if it is possible to retrieve more information about more ports. Right now I believe you are only retrieving from the major ports.

**Comment by samuel-pratt** [comment]
Sorry for the long display on responding to this, I think the scope for this api was just on ports with dynamic info (different times/capacities), but if there's an interest for it I can add an extra endpoint that would contain just the departure times for all the smaller ports separate from the main schedule object.
