### ISSUE TITLE
Code doesn’t have reference to Bowen Island Ferries, despite readme saying it should work.

### ISSUE THREAD

**Issue by cnrlw** [samuel-pratt/bc-ferries-api#24]
I can’t seem to find reference to Bowen Island (Snug Cove) in the code, and I can’t get the API to return any results for Bowen, but the README says it is built to reference Bowen island as a departure and destination.

**Comment by samuel-pratt** [comment]
That's leftover from before I ported this over to go. I'll do a cleanup this weekend and remove any unused ports.

**Comment by samuel-pratt** [comment]
I've removed the reference to Bowen Island for now. I'm planning on adding the smaller ports back sometime in the future.

**Comment by cnrlw** [comment]
Ah, ok. Thanks for the update.

I live on Bowen and have made a simple iOS shortcut that retrieves the
ferry schedule for me (geofenced by whatever side I am on). I'm scraping
their website to do so, but the markup is a bit unreliable / annoying to
work with so I was thinking of using your API instead. FWIW.

Thanks for building and sharing your work!

**Comment by samuel-pratt** [comment]
My main concern was if the core schedule object would get too crowded, but maybe it could work to add another one. So you request the base url, it returns an object with schedule, scraped at, and another entry for the routes that don't report capacities. 

Instead of each route containing an array of objects like the schedule, it could just be an array of strings for each route. Would that work for your use case?

**Comment by cnrlw** [comment]
Yeah I think that would work for what I need.

**Comment by samuel-pratt** [comment]
Perfect, I'll aim to implement that this week.

**Comment by cnrlw** [comment]
Amazing!

**Comment by samuel-pratt** [comment]
Small update on this, there are so many more small terminals than i thought. I'm working through them but I might be updating it just with a few to start.

**Comment by cnrlw** [comment]
Thanks for the update.

**Comment by samuel-pratt** [comment]
Sorry for the late update on this, I made a few attempts to add all the smaller terminals to this api but there are just so many. I think I'm going to keep this api to routes that report capacity, and look at creating a separate one in the future that focuses only on schedules. The scrape each minute method doesn't make sense with mostly static data.

**Comment by davidascher** [comment]
Fyi I made islandtimes.ca just for fun and with no sophistication.

**Comment by samuel-pratt** [comment]
> Fyi I made islandtimes.ca just for fun and with no sophistication.

Just trying to give a heads up to anyone using this api, I have made a large update that will break current uses and route codes will need to be updated. You can check the readme for info on the new routes, and a sample response from the api.

**Comment by davidascher** [comment]
Noted.  I don't use the API.  Change at will from my PoV.
