### ISSUE TITLE
BC Ferry Times Data Bug

### ISSUE THREAD

**Issue by pbadams** [samuel-pratt/bc-ferries-api#29]
Hi @samuel-pratt, leaving a bug report for BC Ferry app here as I couldn't find an option to send feedback in the app.

There might be a bug in the data API when querying a route before the first sailing of the day. The app is reporting "No more departures today" when I try to lookup HSB to LNG at 07:28 (before first scheduled sailing from HSB to LNG at 07:30) This also gives an error when trying reverse route from LNG to HSB before the first sailing from HSB.

After first sailing, the view is properly populated. 

Before First Sailing
![image](https://user-images.githubusercontent.com/136543/172407757-aab753d3-5d26-4f9f-8855-3face171a1a1.jpeg)

After First Sailing
![image](https://user-images.githubusercontent.com/136543/172408819-f534d0e3-7a65-475f-8490-0d6ade62b40e.jpeg)

Cheers,
Paul A. (Sunshine Coast, BC)

**Comment by samuel-pratt** [comment]
Thanks for opening an issue, I really should just add a feedback / bug report spot in the app.

I'm not sure what this could be but I'll see if I can reproduce it tomorrow morning before the first sailing.

**Comment by samuel-pratt** [comment]
I've checked this a few mornings and haven't been able to reproduce the issue. I'll keep an eye out for it and will be adding integration testing soon to check for issues like this as they pop up. My hope is that the BC Ferries website hadn't updated for that morning yet.

I'll check for this again, but I'm not sure if there's a fix I can do at this right now.

Thanks for downloading Ferry Times and reporting the issue, I really appreciate it!
