### ISSUE TITLE
ISO8601 format for scrapedAt

### ISSUE THREAD

**Issue by pbadams** [samuel-pratt/bc-ferries-api#34]
I'm looking to build a JSON Schema for the API. This will help others build language wrappers for the returned JSON.

 I'm hitting a JSON Schema validation error on `scrapedAt` because it's not strict [ISO8601](https://www.iso.org/iso-8601-date-and-time-format.html) format. It appears `scrapedAt` is way to precise, with too many microseconds. My current workaround to define `scrapedAt` as a `string` in the schema, but that defeats the purpose of strict typing and will make language wrapping a little harder.

Any chance of updating the code to adhere to strict ISO8601 for where possible?

**Comment by pbadams** [comment]
This library might be a viable solution: https://github.com/relvacode/iso8601

**Comment by samuel-pratt** [comment]
Forgot to close this before, this was added in this commit: https://github.com/samuel-pratt/bc-ferries-api/commit/990cf650b36398a05865243e961ecae98e551fa1
