### ISSUE TITLE
API Returning empty responses

### ISSUE THREAD

**Issue by daytonturner** [samuel-pratt/bc-ferries-api#35]
Hi Sam!

Just noticed the API is returning empty payload responses, not sure why, or if you could take a look

Also, I downloaded the API from the Git repo to attempt to run / debug myself, but not sure the proper way to run the Go app.  Do you have any docs you can include?

Thanks again!

**Comment by samuel-pratt** [comment]
Hi Dayton!

The BC Ferries site was down for much of Monday and I don't currently have a proper error message for when the scraping returns an error. For my apps I just check if the response is empty and display an error message if they are, but maybe a proper error response would be good to add.


To run a go program you can install go here: https://go.dev/doc/install

Then run `go build` and `./bc-ferries-api` (on mac at least, running the .exe might be different on windows).

I'll make sure to add these steps to the README soon.

**Comment by daytonturner** [comment]
Silly me - I was using 'go run' and wondering why it wasnt working.  Got it!  Thanks :) 

I spent most of my time in python these days, but I can give Go a shot and add some error handling and PR it for you.
