### ISSUE TITLE
Any way to check reservation availability?

### ISSUE THREAD

**Issue by o7-machinehum** [samuel-pratt/bc-ferries-api#36]
Say I want to sail out on a day, and all the reservations are filled up, is there a way to check if resos become available periodically? This would be a super cool function.

**Comment by samuel-pratt** [comment]
I don't currently have it built into this api but there are similar projects that do that sort of thing.

Here's 2 I found:
https://github.com/GriffinLedingham/bcferries-reservation-finder
https://github.com/adrienemery/bcferries
