### ISSUE TITLE
Wrong fill details for next day "(Tomorrow)" sailings 

### ISSUE THREAD

**Issue by shohct** [samuel-pratt/bc-ferries-api#46]
For both V1 and V2 of the API, next day sailings (identified by "(Tomorrow)") have wrong fill details. 

Example from BC Ferries website:
![sailings](https://github.com/samuel-pratt/bc-ferries-api/assets/20247151/310e92df-c501-4dcd-af9a-ff4382c3b919)

API returns:
![api](https://github.com/samuel-pratt/bc-ferries-api/assets/20247151/7f732ced-e8ca-49ae-ad1f-5ea4a6a95ac9)

From scraper.go: 

- Fill is taken from `reducedArray[2]`,
- CarFill from `reducedArray[3]`, and 
- OversizeFill from `reducedArray[4]`.

But seems like for next day sailings, it should be 1 index higher, where:

- Fill should be taken from `reducedArray[3]`,
- CarFill from `reducedArray[4]`, and
- OversizeFill from `reducedArray[5]`.

**Comment by samuel-pratt** [comment]
Fixed in commit a0125b222c264247dca96e08249155d7532526b2, closing for now.
